WITH RECURSIVE GENERATIONS AS
(SELECT ID, PARENT_ID, 1 AS GENERATION
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
UNION ALL
 (
     SELECT e.ID, e.PARENT_ID, g.GENERATION + 1 AS GENERATION
     FROM ECOLI_DATA AS e
     INNER JOIN GENERATIONS g
     ON e.PARENT_ID = g.ID
 )
)

SELECT ID
FROM GENERATIONS AS g
WHERE g.GENERATION = 3
ORDER BY ID ASC
