SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT s.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT s.USER_ID) / TOTAL_USER, 1) AS PUCHASED_RATIO
FROM (
    SELECT 
        USER_ID,
        COUNT(USER_ID) OVER() as TOTAL_USER
    FROM USER_INFO
    WHERE YEAR(JOINED) = "2021"
) a 
LEFT JOIN ONLINE_SALE s USING(USER_ID)
GROUP BY YEAR, MONTH
HAVING COUNT(s.USER_ID) > 0
ORDER BY YEAR, MONTH;