WITH TEMP AS (
SELECT 
    HISTORY_ID,
    CAR_ID,
    CAR_TYPE,
    DAILY_FEE,
    DATEDIFF(END_DATE,START_DATE)+1 AS DAY,
    CASE 
        WHEN DATEDIFF(END_DATE,START_DATE)+1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE,START_DATE)+1 BETWEEN 30 AND 89 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90 THEN '90일 이상'
        ELSE '7일 미만'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY USING(CAR_ID)
)

SELECT 
    HISTORY_ID,
    CASE 
        WHEN T.DURATION_TYPE = '7일 미만' THEN DAILY_FEE * DAY
        ELSE ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * DAY)
    END AS FEE
FROM TEMP T LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
ON T.CAR_TYPE = P.CAR_TYPE 
AND T.DURATION_TYPE = P.DURATION_TYPE
WHERE T.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC