SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i 
INNER JOIN ITEM_TREE t ON i.ITEM_ID = t.ITEM_ID
WHERE t.PARENT_ITEM_ID in (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = "RARE")
ORDER BY ITEM_ID DESC;