SELECT t.MONTH, t.CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM (SELECT MONTH(START_DATE) AS MONTH, CAR_ID, HISTORY_ID, COUNT(CAR_ID) OVER (PARTITION BY CAR_ID) AS cnt
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
    ) t
WHERE t.cnt >= 5
GROUP BY t.MONTH, t.CAR_ID
ORDER BY t.MONTH, t.CAR_ID DESC;