WITH tmp AS (
    SELECT *, MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS MAX_DEV
    FROM ECOLI_DATA
)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX_DEV - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM tmp
ORDER BY YEAR, YEAR_DEV;
