-- 코드를 입력하세요
SELECT his.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY his JOIN CAR_RENTAL_COMPANY_CAR car ON car.CAR_ID = his.CAR_ID
WHERE CAR_TYPE = "세단" AND SUBSTR(START_DATE,1,7) = "2022-10"
GROUP BY his.CAR_ID
ORDER BY his.CAR_ID DESC;